## 02: Preprocessing
Merge phenotype + environment + genomic data into one flat feature matrix ready for modeling.

Flip `SAMPLE_MODE = False` once ready to run on full data.

In [1]:
import pandas as pd
import numpy as np
import os
import re

SAMPLE_MODE = False  #flip to False for full run

#paths
if SAMPLE_MODE:
    PHENO_PATH = '../data/raw/sample_data/sample_C1_phenotype_100rows.csv'
    ENV_PATH   = '../data/raw/sample_data/sample_environmental_20rows.csv'
    def geno_path(cluster_id, pop_num):
        return f'../data/raw/sample_data/sample_C{cluster_id}.{pop_num}_100rows.csv'
else:
    PHENO_PATH = '../data/raw/C1_Phenotype_Data_V2.csv'
    ENV_PATH   = '../data/raw/environmental_features.csv'
    def geno_path(cluster_id, pop_num):
        return f'../data/raw/genotypes/C{cluster_id}/ImputedPopulationsC{cluster_id}/C{cluster_id}.{pop_num}_Imputed.csv'

OUTPUT_PATH = '../data/processed/merged_sample.csv' if SAMPLE_MODE else '../data/processed/merged_full.csv'
print('SAMPLE_MODE:', SAMPLE_MODE)

SAMPLE_MODE: False

### 1. Load raw data

In [2]:
pheno = pd.read_csv(PHENO_PATH)
env   = pd.read_csv(ENV_PATH)
print('Raw pheno:', pheno.shape)
print('Env:      ', env.shape)

Raw pheno: (536936, 33)
Env:       (1185, 86)

/tmp/job.346229/ipykernel_223872/4244469098.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  pheno = pd.read_csv(PHENO_PATH)

### 2. Clean phenotype
Drop junk columns left over from the pre-merge, normalize the YEAR column name, and parse `LINE_UNIQUE_ID` into its three components.

In [3]:
JUNK_COLS = [
    'Unnamed: 0', 'Unnamed: 0_x', 'Unnamed: 0_y',
    'projects_x', 'projects_y',
    'FILE_LIST', 'shorthand_x', 'shorthand_y',
    'YEAR_y', 'projectID', 'MAB_PROJECT_ID', 'GENERATION_NAME',
]
pheno = pheno.drop(columns=[c for c in JUNK_COLS if c in pheno.columns])

# normalize YEAR (sample pheno has YEAR_x due to pre-merge duplication)
if 'YEAR_x' in pheno.columns:
    pheno = pheno.rename(columns={'YEAR_x': 'YEAR'})

# parse LINE_UNIQUE_ID: 'C1.1.191' -> cluster=1, pop=1, line=191
parsed = pheno['LINE_UNIQUE_ID'].str.extract(r'^C(\d+)\.(\d+)\.(\d+)$')
parsed.columns = ['CLUSTER_ID', 'POP_NUM', 'LINE_NUM']
pheno[['CLUSTER_ID', 'POP_NUM', 'LINE_NUM']] = parsed

n_unparsed = pheno['LINE_UNIQUE_ID'][parsed['LINE_NUM'].isnull()].nunique()
print(f"Dropping {parsed['LINE_NUM'].isnull().sum()} rows with unparseable LINE_UNIQUE_ID ({n_unparsed} unique IDs)")

pheno = pheno[parsed['LINE_NUM'].notna()].copy()
pheno['CLUSTER_ID'] = pheno['CLUSTER_ID'].astype(int)
pheno['POP_NUM']    = pheno['POP_NUM'].astype(int)
pheno['LINE_NUM']   = pheno['LINE_NUM'].astype(int)
print(f'Clean pheno: {pheno.shape}  |  LINE_UNIQUE_ID parse failures: {n_unparsed}')
pheno[['LINE_UNIQUE_ID', 'CLUSTER_ID', 'POP_NUM', 'LINE_NUM']].head(3)

Dropping 4488 rows with unparseable LINE_UNIQUE_ID (693 unique IDs)
Clean pheno: (532448, 24)  |  LINE_UNIQUE_ID parse failures: 693

  LINE_UNIQUE_ID  CLUSTER_ID  POP_NUM  LINE_NUM
0       C1.1.191           1        1       191
1       C1.1.193           1        1       193
2        C1.1.62           1        1        62

### 3. Merge phenotype + environment
Left join on `YEAR + LOC` so every phenotype row keeps its env features (or gets NaN if the env row is missing — expected in sample mode).

In [4]:
pheno_env = pheno.merge(env, on=['YEAR', 'LOC'], how='left')
print(f'Pheno+Env shape: {pheno_env.shape}')

env_feat_cols = [c for c in env.columns if c not in ('YEAR', 'LOC')]
rows_no_env = pheno_env[env_feat_cols].isnull().all(axis=1).sum()
print(f'Rows with no env match: {rows_no_env}/{len(pheno_env)} (expected ~all in sample mode)')

Pheno+Env shape: (532448, 108)
Rows with no env match: 0/532448 (expected ~all in sample mode)

### 4. Merge with genomic data
For each (cluster, population) group in the phenotype, load the matching genomic file, filter to progeny rows only (dropping parent PIDs), and left-join on `LINE_NUM`.

In [10]:
def load_geno(cluster_id, pop_num):
    path = geno_path(cluster_id, pop_num)
    if not os.path.exists(path):
        print(f'  [MISS] {path}')
        return None
    geno = pd.read_csv(path, index_col=0)
    progeny_mask = geno.index.astype(str).str.match(r'^\d{11}$')
    geno = geno.loc[progeny_mask].copy()
    geno['LINE_NUM'] = geno.index.astype(int)
    return geno

groups = pheno_env.groupby(['CLUSTER_ID', 'POP_NUM'], sort=False)
print(f'Populations to process: {groups.ngroups}')

first_chunk = True
for (cluster_id, pop_num), group in groups:
    geno = load_geno(cluster_id, int(pop_num))
    if geno is not None:
        merged = group.merge(
            geno.drop(columns=['LINE_NUM']).assign(LINE_NUM=geno['LINE_NUM']),
            on='LINE_NUM', how='left')
        if len(group) and merged.shape[1] > group.shape[1]:
            print(f'  C{cluster_id}.{pop_num}: {len(group)} rows -> {merged.shape[1]} cols')
    else:
        merged = group.copy()
    
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    merged.to_csv(OUTPUT_PATH, mode='w' if first_chunk else 'a',
                  header=first_chunk, index=False)
    first_chunk = False

print(f'\nDone. Saved -> {OUTPUT_PATH}')

Populations to process: 495
  C1.1: 1070 rows -> 3019 cols
  C1.2: 795 rows -> 3019 cols
  C1.3: 1458 rows -> 3019 cols
  C1.4: 1034 rows -> 3019 cols
  C1.5: 666 rows -> 3019 cols
  C1.6: 843 rows -> 3019 cols
  C1.7: 808 rows -> 3019 cols
  C1.8: 1190 rows -> 3019 cols
  C1.9: 816 rows -> 3019 cols
  C1.10: 1032 rows -> 3019 cols
  C1.11: 811 rows -> 3019 cols
  C1.12: 1223 rows -> 3019 cols
  C1.13: 1116 rows -> 3019 cols
  C1.14: 1198 rows -> 3019 cols
  C1.15: 1008 rows -> 3019 cols
  C1.16: 787 rows -> 3019 cols
  C1.17: 680 rows -> 3019 cols
  C1.18: 819 rows -> 3019 cols
  C1.19: 819 rows -> 3019 cols
  C1.20: 1190 rows -> 3019 cols
  C1.21: 1148 rows -> 3019 cols
  C1.22: 960 rows -> 3019 cols
  C1.23: 930 rows -> 3019 cols
  C1.24: 1329 rows -> 3019 cols
  C1.25: 1285 rows -> 3019 cols
  C1.26: 1352 rows -> 3019 cols
  C1.27: 1362 rows -> 3019 cols
  C1.28: 1389 rows -> 3019 cols
  C1.29: 1239 rows -> 3019 cols
  C1.30: 1231 rows -> 3019 cols
  C1.31: 1502 rows -> 3019 cols
  C1.32: 1392 rows -> 3019 cols
  C1.33: 885 rows -> 3019 cols
  C1.35: 1376 rows -> 3019 cols
  C1.36: 1127 rows -> 3019 cols
  C1.37: 1183 rows -> 3019 cols
  C1.38: 1016 rows -> 3019 cols
  C1.40: 801 rows -> 3019 cols
  C1.41: 1143 rows -> 3019 cols
  C1.42: 1211 rows -> 3019 cols
  C1.43: 938 rows -> 3019 cols
  C1.44: 1200 rows -> 3019 cols
  C1.45: 1197 rows -> 3019 cols
  C1.46: 1205 rows -> 3019 cols
  C1.47: 510 rows -> 3019 cols
  C1.48: 744 rows -> 3019 cols
  C1.49: 1366 rows -> 3019 cols
  C1.50: 736 rows -> 3019 cols
  C1.51: 1217 rows -> 3019 cols
  C1.52: 978 rows -> 3019 cols
  C1.53: 740 rows -> 3019 cols
  C1.54: 930 rows -> 3019 cols
  C1.55: 1392 rows -> 3019 cols
  C1.56: 1067 rows -> 3019 cols
  C1.57: 744 rows -> 3019 cols
  C1.58: 720 rows -> 3019 cols
  C1.59: 736 rows -> 3019 cols
  C1.60: 1070 rows -> 3019 cols
  C1.61: 1416 rows -> 3019 cols
  C1.62: 1417 rows -> 3019 cols
  C1.63: 736 rows -> 3019 cols
  C1.64: 1423 rows -> 3019 cols
  C1.65: 1060 rows -> 3019 cols
  C1.66: 912 rows -> 3019 cols
  C1.67: 1454 rows -> 3019 cols
  C1.68: 1381 rows -> 3019 cols
  C1.69: 1216 rows -> 3019 cols
  C1.70: 709 rows -> 3019 cols
  C1.71: 665 rows -> 3019 cols
  C1.72: 714 rows -> 3019 cols
  C1.73: 1142 rows -> 3019 cols
  C1.74: 1128 rows -> 3019 cols
  C1.75: 921 rows -> 3019 cols
  C1.76: 1439 rows -> 3019 cols
  C1.77: 1233 rows -> 3019 cols
  C1.78: 1054 rows -> 3019 cols
  C1.79: 1097 rows -> 3019 cols
  C1.80: 1427 rows -> 3019 cols
  C1.81: 1044 rows -> 3019 cols
  C1.82: 1430 rows -> 3019 cols
  C1.83: 1128 rows -> 3019 cols
  C1.84: 1227 rows -> 3019 cols
  C1.85: 1253 rows -> 3019 cols
  C1.86: 1439 rows -> 3019 cols
  C1.87: 1401 rows -> 3019 cols
  C1.88: 1428 rows -> 3019 cols
  C1.89: 1257 rows -> 3019 cols
  C1.90: 1191 rows -> 3019 cols
  C1.91: 1103 rows -> 3019 cols
  C1.92: 1061 rows -> 3019 cols
  C1.93: 1251 rows -> 3019 cols
  C1.94: 1243 rows -> 3019 cols
  C1.95: 1429 rows -> 3019 cols
  C1.96: 1255 rows -> 3019 cols
  C1.97: 1284 rows -> 3019 cols
  C1.98: 1462 rows -> 3019 cols
  C1.99: 1412 rows -> 3019 cols
  C1.100: 1285 rows -> 3019 cols
  C1.101: 1229 rows -> 3019 cols
  C1.102: 2452 rows -> 3019 cols
  C1.103: 1555 rows -> 3019 cols
  C1.104: 682 rows -> 3019 cols
  C1.105: 965 rows -> 3019 cols
  C1.106: 1536 rows -> 3019 cols

/tmp/job.346229/ipykernel_223872/3685475672.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  geno = pd.read_csv(path, index_col=0)

  C1.107: 2728 rows -> 3019 cols
  C1.108: 1381 rows -> 3019 cols
  C1.109: 1335 rows -> 3019 cols
  C1.110: 1449 rows -> 3019 cols
  C1.111: 1395 rows -> 3019 cols
  C1.112: 1228 rows -> 3019 cols
  C1.113: 1447 rows -> 3019 cols
  C1.114: 1050 rows -> 3019 cols
  C1.115: 1380 rows -> 3019 cols
  C1.116: 1243 rows -> 3019 cols
  C1.117: 1430 rows -> 3019 cols
  C1.118: 1042 rows -> 3019 cols
  C1.119: 1220 rows -> 3019 cols
  C1.120: 1260 rows -> 3019 cols
  C1.121: 1471 rows -> 3019 cols
  C1.122: 1219 rows -> 3019 cols
  C1.123: 1480 rows -> 3019 cols
  C1.124: 719 rows -> 3019 cols
  C1.127: 736 rows -> 3019 cols
  C1.128: 1408 rows -> 3019 cols
  C1.129: 1466 rows -> 3019 cols
  C1.130: 1440 rows -> 3019 cols
  C1.131: 1258 rows -> 3019 cols
  C1.132: 1218 rows -> 3019 cols
  C1.133: 1432 rows -> 3019 cols
  C1.134: 1195 rows -> 3019 cols
  C1.135: 1077 rows -> 3019 cols
  C1.136: 1260 rows -> 3019 cols
  C1.137: 1440 rows -> 3019 cols
  C1.138: 1245 rows -> 3019 cols
  C1.139: 544 rows -> 3019 cols
  C1.140: 1440 rows -> 3019 cols
  C1.141: 1432 rows -> 3019 cols
  C1.142: 1044 rows -> 3019 cols
  C1.143: 1253 rows -> 3019 cols
  C1.144: 1301 rows -> 3019 cols
  C1.145: 900 rows -> 3019 cols
  C1.146: 922 rows -> 3019 cols
  C1.147: 1070 rows -> 3019 cols
  C1.148: 1251 rows -> 3019 cols
  C1.149: 1437 rows -> 3019 cols
  C1.150: 1527 rows -> 3019 cols
  C1.151: 1406 rows -> 3019 cols
  C1.152: 1503 rows -> 3019 cols
  C1.153: 1431 rows -> 3019 cols
  C1.154: 1428 rows -> 3019 cols
  C1.155: 1190 rows -> 3019 cols
  C1.156: 1224 rows -> 3019 cols
  C1.157: 1424 rows -> 3019 cols
  C1.158: 715 rows -> 3019 cols
  C1.159: 1260 rows -> 3019 cols
  C1.160: 1244 rows -> 3019 cols
  C1.161: 1390 rows -> 3019 cols
  C1.162: 1260 rows -> 3019 cols
  C1.163: 1128 rows -> 3019 cols
  C1.164: 1088 rows -> 3019 cols
  C1.165: 1098 rows -> 3019 cols
  C1.166: 1077 rows -> 3019 cols
  C1.167: 1432 rows -> 3019 cols
  C1.168: 1286 rows -> 3019 cols
  C1.169: 1485 rows -> 3019 cols
  C1.170: 1440 rows -> 3019 cols
  C1.171: 1430 rows -> 3019 cols
  C1.172: 1295 rows -> 3019 cols
  C1.173: 1466 rows -> 3019 cols
  C1.174: 398 rows -> 3019 cols
  C1.175: 1470 rows -> 3019 cols
  C1.176: 1431 rows -> 3019 cols
  C1.177: 1308 rows -> 3019 cols
  C1.178: 1235 rows -> 3019 cols
  C1.179: 1463 rows -> 3019 cols
  C1.180: 1446 rows -> 3019 cols
  C1.181: 1258 rows -> 3019 cols
  C1.182: 1408 rows -> 3019 cols
  C1.183: 438 rows -> 3019 cols
  C1.184: 439 rows -> 3019 cols
  C1.185: 1472 rows -> 3019 cols
  C1.186: 1472 rows -> 3019 cols
  C1.187: 467 rows -> 3019 cols
  C1.188: 1366 rows -> 3019 cols
  C1.189: 870 rows -> 3019 cols
  C1.190: 1044 rows -> 3019 cols
  C1.191: 873 rows -> 3019 cols
  C1.192: 1382 rows -> 3019 cols
  C1.193: 1189 rows -> 3019 cols
  C1.194: 1253 rows -> 3019 cols
  C1.195: 1225 rows -> 3019 cols
  C1.196: 784 rows -> 3019 cols
  C1.197: 1464 rows -> 3019 cols
  C1.198: 1288 rows -> 3019 cols
  C1.199: 1468 rows -> 3019 cols
  C1.200: 1288 rows -> 3019 cols
  C1.201: 1086 rows -> 3019 cols
  C1.202: 1376 rows -> 3019 cols
  C1.203: 784 rows -> 3019 cols
  C1.204: 1344 rows -> 3019 cols
  C1.205: 1376 rows -> 3019 cols
  C1.206: 1215 rows -> 3019 cols
  C1.207: 1300 rows -> 3019 cols
  C1.208: 1477 rows -> 3019 cols
  C1.209: 1056 rows -> 3019 cols
  C1.210: 1453 rows -> 3019 cols
  C1.211: 1286 rows -> 3019 cols
  C1.212: 1384 rows -> 3019 cols
  C1.213: 1210 rows -> 3019 cols
  C1.214: 1358 rows -> 3019 cols
  C1.215: 1467 rows -> 3019 cols
  C1.216: 1288 rows -> 3019 cols
  C1.217: 1480 rows -> 3019 cols
  C1.218: 1352 rows -> 3019 cols
  C1.219: 1407 rows -> 3019 cols
  C1.220: 1470 rows -> 3019 cols
  C1.221: 1463 rows -> 3019 cols
  C1.222: 1225 rows -> 3019 cols
  C1.223: 1432 rows -> 3019 cols
  C1.224: 960 rows -> 3019 cols
  C1.225: 1300 rows -> 3019 cols
  C1.226: 870 rows -> 3019 cols
  C1.227: 1016 rows -> 3019 cols
  C1.228: 1530 rows -> 3019 cols
  C1.229: 1329 rows -> 3019 cols
  C1.230: 1238 rows -> 3019 cols
  C1.231: 1447 rows -> 3019 cols
  C1.232: 1460 rows -> 3019 cols
  C1.233: 1461 rows -> 3019 cols
  C1.234: 1615 rows -> 3019 cols
  C1.235: 1833 rows -> 3019 cols
  C1.236: 1827 rows -> 3019 cols

/tmp/job.346229/ipykernel_223872/3685475672.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  geno = pd.read_csv(path, index_col=0)

  C1.237: 2728 rows -> 3019 cols
  C1.238: 1790 rows -> 3019 cols
  C1.239: 1435 rows -> 3019 cols
  C1.240: 1448 rows -> 3019 cols
  C1.241: 1448 rows -> 3019 cols
  C1.242: 1457 rows -> 3019 cols
  C1.243: 1425 rows -> 3019 cols
  C1.244: 1462 rows -> 3019 cols
  C1.245: 1439 rows -> 3019 cols
  C1.246: 1480 rows -> 3019 cols
  C1.247: 1471 rows -> 3019 cols
  C1.248: 1456 rows -> 3019 cols
  C1.249: 1237 rows -> 3019 cols
  C1.250: 1281 rows -> 3019 cols
  C1.251: 1611 rows -> 3019 cols
  C1.252: 1406 rows -> 3019 cols
  C1.253: 1260 rows -> 3019 cols
  C1.254: 1312 rows -> 3019 cols
  C1.255: 1416 rows -> 3019 cols
  C1.256: 1392 rows -> 3019 cols
  C1.257: 1464 rows -> 3019 cols
  C1.258: 1440 rows -> 3019 cols
  C1.259: 2155 rows -> 3019 cols
  C1.260: 1436 rows -> 3019 cols
  C1.261: 1440 rows -> 3019 cols
  C1.262: 1063 rows -> 3019 cols
  C1.263: 1423 rows -> 3019 cols
  C1.264: 1438 rows -> 3019 cols
  C1.265: 1431 rows -> 3019 cols
  C1.266: 1252 rows -> 3019 cols
  C1.267: 1430 rows -> 3019 cols
  C1.268: 1368 rows -> 3019 cols
  C1.269: 1039 rows -> 3019 cols
  C1.270: 1464 rows -> 3019 cols
  C1.271: 1463 rows -> 3019 cols
  C1.272: 1166 rows -> 3019 cols
  C1.273: 1423 rows -> 3019 cols
  C1.274: 1256 rows -> 3019 cols
  C1.275: 1418 rows -> 3019 cols
  C1.276: 1431 rows -> 3019 cols
  C1.277: 1236 rows -> 3019 cols
  C1.278: 1439 rows -> 3019 cols
  C1.279: 1343 rows -> 3019 cols
  C1.280: 1423 rows -> 3019 cols
  C1.281: 1239 rows -> 3019 cols
  C1.282: 1424 rows -> 3019 cols
  C1.283: 1260 rows -> 3019 cols
  C1.284: 1062 rows -> 3019 cols
  C1.285: 1593 rows -> 3019 cols
  C1.286: 1619 rows -> 3019 cols
  C1.287: 1224 rows -> 3019 cols
  C1.288: 744 rows -> 3019 cols
  C1.289: 791 rows -> 3019 cols
  C1.290: 1425 rows -> 3019 cols
  C1.291: 744 rows -> 3019 cols
  C1.292: 744 rows -> 3019 cols
  C1.293: 1256 rows -> 3019 cols
  C1.294: 1284 rows -> 3019 cols
  C1.295: 1397 rows -> 3019 cols
  C1.296: 531 rows -> 3019 cols
  C1.297: 1002 rows -> 3019 cols
  C1.298: 1228 rows -> 3019 cols
  C1.299: 1665 rows -> 3019 cols
  C1.300: 1421 rows -> 3019 cols
  C1.301: 1285 rows -> 3019 cols
  C1.302: 1092 rows -> 3019 cols
  C1.303: 1636 rows -> 3019 cols
  C1.304: 1129 rows -> 3019 cols
  C1.305: 1228 rows -> 3019 cols
  C1.306: 1187 rows -> 3019 cols
  C1.307: 1282 rows -> 3019 cols
  C1.308: 1191 rows -> 3019 cols
  C1.309: 1202 rows -> 3019 cols
  C1.310: 1066 rows -> 3019 cols
  C1.311: 1051 rows -> 3019 cols
  C1.312: 1213 rows -> 3019 cols
  C1.313: 1234 rows -> 3019 cols
  C1.314: 1487 rows -> 3019 cols
  C1.315: 1291 rows -> 3019 cols
  C1.316: 1375 rows -> 3019 cols
  C1.317: 1297 rows -> 3019 cols
  C1.319: 867 rows -> 3019 cols
  C1.320: 855 rows -> 3019 cols
  C1.321: 1058 rows -> 3019 cols
  C1.322: 637 rows -> 3019 cols
  C1.323: 1189 rows -> 3019 cols
  C1.324: 1084 rows -> 3019 cols
  C1.325: 1421 rows -> 3019 cols
  C1.326: 1061 rows -> 3019 cols
  C1.327: 964 rows -> 3019 cols
  C1.328: 538 rows -> 3019 cols
  C1.329: 1482 rows -> 3019 cols
  C1.330: 1291 rows -> 3019 cols
  C1.331: 849 rows -> 3019 cols
  C1.332: 1471 rows -> 3019 cols
  C1.333: 1135 rows -> 3019 cols
  C1.334: 546 rows -> 3019 cols
  C1.335: 1221 rows -> 3019 cols
  C1.336: 711 rows -> 3019 cols
  C1.337: 926 rows -> 3019 cols
  C1.338: 1016 rows -> 3019 cols
  C1.339: 637 rows -> 3019 cols
  C1.340: 1445 rows -> 3019 cols
  C1.341: 1465 rows -> 3019 cols
  C1.342: 871 rows -> 3019 cols
  C1.343: 893 rows -> 3019 cols
  C1.344: 1429 rows -> 3019 cols
  C1.345: 1569 rows -> 3019 cols
  C1.346: 981 rows -> 3019 cols
  C1.347: 1012 rows -> 3019 cols
  C1.348: 1104 rows -> 3019 cols
  C1.349: 1426 rows -> 3019 cols
  C1.350: 1402 rows -> 3019 cols
  C1.351: 1452 rows -> 3019 cols
  C1.352: 1149 rows -> 3019 cols
  C1.353: 988 rows -> 3019 cols
  C1.354: 1102 rows -> 3019 cols
  C1.355: 920 rows -> 3019 cols
  C1.356: 1450 rows -> 3019 cols
  C1.357: 1023 rows -> 3019 cols
  C1.358: 921 rows -> 3019 cols
  C1.359: 1097 rows -> 3019 cols
  C1.360: 1054 rows -> 3019 cols
  C1.361: 867 rows -> 3019 cols
  C1.362: 1219 rows -> 3019 cols
  C1.363: 1226 rows -> 3019 cols
  C1.364: 1273 rows -> 3019 cols
  C1.365: 1423 rows -> 3019 cols
  C1.366: 1262 rows -> 3019 cols
  C1.367: 732 rows -> 3019 cols
  C1.368: 672 rows -> 3019 cols
  C1.369: 1265 rows -> 3019 cols
  C1.370: 1283 rows -> 3019 cols
  C1.371: 897 rows -> 3019 cols
  C1.372: 861 rows -> 3019 cols
  C1.373: 1216 rows -> 3019 cols
  C1.374: 867 rows -> 3019 cols
  C1.375: 1728 rows -> 3019 cols
  C1.376: 940 rows -> 3019 cols
  C1.377: 331 rows -> 3019 cols
  C1.378: 219 rows -> 3019 cols
  C1.379: 355 rows -> 3019 cols
  C1.380: 613 rows -> 3019 cols
  C1.381: 574 rows -> 3019 cols
  C1.382: 392 rows -> 3019 cols
  C1.383: 685 rows -> 3019 cols
  C1.384: 405 rows -> 3019 cols
  C1.385: 397 rows -> 3019 cols
  C1.386: 507 rows -> 3019 cols
  C1.387: 693 rows -> 3019 cols
  C1.388: 695 rows -> 3019 cols
  C1.389: 477 rows -> 3019 cols
  C1.390: 520 rows -> 3019 cols
  C1.391: 328 rows -> 3019 cols
  C1.392: 244 rows -> 3019 cols
  C1.393: 413 rows -> 3019 cols
  C1.394: 310 rows -> 3019 cols
  C1.395: 366 rows -> 3019 cols
  C1.396: 995 rows -> 3019 cols
  C1.397: 821 rows -> 3019 cols
  C1.398: 825 rows -> 3019 cols
  C1.399: 323 rows -> 3019 cols
  C1.400: 452 rows -> 3019 cols
  C1.401: 423 rows -> 3019 cols
  C1.402: 528 rows -> 3019 cols
  C1.403: 574 rows -> 3019 cols
  C1.404: 780 rows -> 3019 cols
  C1.405: 353 rows -> 3019 cols
  C1.406: 899 rows -> 3019 cols
  C1.407: 340 rows -> 3019 cols
  C1.408: 511 rows -> 3019 cols
  C1.409: 435 rows -> 3019 cols
  C1.410: 400 rows -> 3019 cols
  C1.411: 346 rows -> 3019 cols
  C1.412: 797 rows -> 3019 cols
  C1.413: 222 rows -> 3019 cols
  C1.414: 410 rows -> 3019 cols
  C1.415: 300 rows -> 3019 cols
  C1.416: 672 rows -> 3019 cols
  C1.417: 704 rows -> 3019 cols
  C1.418: 382 rows -> 3019 cols
  C1.419: 412 rows -> 3019 cols
  C1.420: 269 rows -> 3019 cols
  C1.421: 756 rows -> 3019 cols
  C1.422: 802 rows -> 3019 cols
  C1.423: 683 rows -> 3019 cols
  C1.424: 430 rows -> 3019 cols
  C1.425: 384 rows -> 3019 cols
  C1.426: 518 rows -> 3019 cols
  C1.427: 199 rows -> 3019 cols
  C1.428: 414 rows -> 3019 cols
  C1.429: 581 rows -> 3019 cols
  C1.430: 605 rows -> 3019 cols
  C1.431: 313 rows -> 3019 cols
  C1.432: 904 rows -> 3019 cols
  C1.433: 703 rows -> 3019 cols
  C1.434: 808 rows -> 3019 cols
  C1.435: 1060 rows -> 3019 cols
  C1.436: 969 rows -> 3019 cols
  C1.437: 869 rows -> 3019 cols
  C1.438: 1025 rows -> 3019 cols
  C1.439: 438 rows -> 3019 cols
  C1.440: 510 rows -> 3019 cols
  C1.441: 528 rows -> 3019 cols
  C1.442: 689 rows -> 3019 cols
  C1.443: 387 rows -> 3019 cols
  C1.444: 1078 rows -> 3019 cols
  C1.445: 689 rows -> 3019 cols
  C1.446: 411 rows -> 3019 cols
  C1.447: 525 rows -> 3019 cols
  C1.448: 1013 rows -> 3019 cols
  C1.449: 509 rows -> 3019 cols
  C1.450: 414 rows -> 3019 cols
  C1.451: 517 rows -> 3019 cols
  C1.452: 1235 rows -> 3019 cols
  C1.453: 1067 rows -> 3019 cols
  C1.454: 1310 rows -> 3019 cols
  C1.455: 811 rows -> 3019 cols
  C1.456: 519 rows -> 3019 cols
  C1.457: 302 rows -> 3019 cols
  C1.458: 852 rows -> 3019 cols
  C1.459: 905 rows -> 3019 cols
  C1.460: 428 rows -> 3019 cols
  C1.461: 853 rows -> 3019 cols
  C1.462: 440 rows -> 3019 cols
  C1.463: 979 rows -> 3019 cols
  C1.464: 527 rows -> 3019 cols
  C1.465: 524 rows -> 3019 cols
  C1.466: 1458 rows -> 3019 cols
  C1.467: 1046 rows -> 3019 cols
  C1.468: 1226 rows -> 3019 cols
  C1.469: 315 rows -> 3019 cols
  C1.470: 1408 rows -> 3019 cols
  C1.471: 602 rows -> 3019 cols
  C1.472: 865 rows -> 3019 cols
  C1.473: 320 rows -> 3019 cols
  C1.474: 1423 rows -> 3019 cols
  C1.475: 800 rows -> 3019 cols
  C1.476: 852 rows -> 3019 cols
  C1.477: 1283 rows -> 3019 cols
  C1.478: 330 rows -> 3019 cols
  C1.479: 963 rows -> 3019 cols
  C1.480: 412 rows -> 3019 cols
  C1.481: 731 rows -> 3019 cols
  C1.482: 1077 rows -> 3019 cols
  C1.483: 386 rows -> 3019 cols
  C1.484: 492 rows -> 3019 cols
  C1.485: 273 rows -> 3019 cols
  C1.486: 449 rows -> 3019 cols
  C1.487: 324 rows -> 3019 cols
  C1.488: 941 rows -> 3019 cols
  C1.489: 949 rows -> 3019 cols
  C1.490: 1102 rows -> 3019 cols

  C1.491: 495 rows -> 3019 cols
  C1.492: 838 rows -> 3019 cols
  C1.493: 583 rows -> 3019 cols
  C1.494: 255 rows -> 3019 cols
  C1.495: 1247 rows -> 3019 cols
  C1.496: 1444 rows -> 3019 cols
  C1.497: 1234 rows -> 3019 cols
  C1.498: 458 rows -> 3019 cols
  C1.499: 914 rows -> 3019 cols
  C1.500: 929 rows -> 3019 cols

Done. Saved -> ../data/processed/merged_full.csv

### 5. Quality check

In [7]:
# Target variable
print(f'YLD_BE missing: {df["YLD_BE"].isnull().sum()}/{len(df)}')

# SNP missingness (pre-imputed files should be ~0%)
snp_cols = [c for c in df.columns if c.startswith('M')]
if snp_cols:
    snp_null_pct = df[snp_cols].isnull().mean().mean() * 100
    print(f'SNP cols: {len(snp_cols)}  |  mean missingness: {snp_null_pct:.1f}%')
else:
    print('No SNP columns merged (check geno file match)')

# Env missingness
env_null_pct = df[env_feat_cols].isnull().mean().mean() * 100
print(f'Env feat missingness: {env_null_pct:.1f}%')

# Preview
key_cols = ['LINE_UNIQUE_ID', 'YEAR', 'LOC', 'YLD_BE'] + snp_cols[:3] + env_feat_cols[:3]
df[[c for c in key_cols if c in df.columns]].head(3)

YLD_BE missing: 20806/532448
SNP cols: 2912  |  mean missingness: 14.1%
Env feat missingness: 0.0%

,LINE_UNIQUE_ID,YEAR,LOC,YLD_BE,MST,M00003409443,M00000005000,X04_PRCP,X05_PRCP,X06_PRCP
0,C1.1.191,2001,NEDA,156.052,19.7,1.0,1.0,132.4,149.2,65.4
1,C1.1.193,2001,NEDA,150.685,20.2,1.0,1.0,132.4,149.2,65.4
2,C1.1.62,2001,IAPR,157.218,19.1,1.0,1.0,136.9,158.3,51.5

### 6. Save

SAMPLE DATA INTERP:

The two 100% missingness numbers are both sample artifacts. The env miss at 100% is the same LOC mismatch seen in the 01_eda file. The SNP miss at 65.5% comes directly from our EDA finding that the sample geno file covers lines 1-100, but pheno lines mostly run 62-198, so only line 62 and a handful of low-numbered lines matched. Every unmatched row gets NaN across all 2912 SNP columns. That math lands us right around 60-65% missingness. Row 2 on line 62 shows actual SNP values (1.0, 1.0) while rows 0-1 (lines 191, 193) are all NaN.

When we flip to SAMPLE_MODE = False:

Env missingness should drop to near 0% (full env file covers all LOC+YEAR combos)
SNP missingness should drop to near 0% (full geno files are pre-imputed, and every pheno line will have a matching geno file)
The geno loop will spin over hundreds of populations instead of 1, so expect a few minutes of runtime

The pipeline is structurally correct & The 3/100 missing YLD_BE is the only real data gap, and those 3 rows need to be dropped before modeling since that's the target.